#!/bin/bash
# set -euo pipefail
set -x

# cleanup X lock and sock
rm -rf /tmp/.X*

URL=${URL:-http://jodel-app.com}

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

rm -rf /tmp/*

if [ -n "$REMOTE_HOST" ]; then
  cat <<EOF > /etc/openvpn.conf
client
nobind
remote-random
remote $REMOTE_HOST $REMOTE_PORT
proto tcp
mute 5
dev tun
<ca>
$( echo -e "$CERT" )
</ca>
auth-user-pass /etc/openvpn.credentials
EOF
  ( umask 0077; echo -e "${VPN_USER}\n${VPN_PASS}" > /etc/openvpn.credentials )
  openvpn --config /etc/openvpn.conf &
fi

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

dropbear -E -F &
DB_PID=$!

Xorg &
X_PID=$!

echo "Waiting for X to be ready"
export DISPLAY=:0

# for balena supervisor versions 1.7.0 and newer (both balenaOS 1.x and 2.x) use this version:
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

# Setting wallpaper and polling X in one!
while ! feh --bg-scale /etc/wallpaper.png; do sleep 1; done
matchbox-window-manager -use_cursor no &

while ! curl -sf -o /dev/null "$URL"; do sleep 1; done

xset -dpms
xset s off
xset s noblank

DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket \
  chromium "$URL" \ 
    --no-sandbox --disable-gpu --disable-software-rasterizer \
    --window-size=1920,1080 --start-fullscreen --kiosk --incognito \
    --noerrdialogs --disable-translate --no-first-run --fast --fast-start \
    --disable-infobars --disable-features=TranslateUI --disk-cache-dir=/dev/null

sleep infinity
